module(load="imudp")
module(load="imtcp")

input(type="imudp" port="514")
input(type="imtcp" port="514")

template(name="RemoteHostLog" type="string"
  string="/var/log/remote/%HOSTNAME%/%$YEAR%-%$MONTH%-%$DAY%.log")

if $fromhost-ip != '127.0.0.1' then {
  action(type="omfile" DynaFile="RemoteHostLog"
         dirCreateMode="0755" fileCreateMode="0644"
         dirOwner="syslog" fileOwner="syslog")
  stop
}
